### ISSUE TITLE
Open the comment space?

### ISSUE THREAD

**Issue by GindaChen** [xuxiaopang/install-ceph-in-one-minute#1]

**Comment by GindaChen** [comment]
I love your post, but there are absolutely no way to find your profile... 
I'm really excited to read your post (even if it written years ago). I'm very fortunate to have the opportunity to work with Sage in my graduate course about Distributed System (Check P1 in http://pages.cs.wisc.edu/~remzi/Classes/739/Fall2018/) and we're still exploring Ceph. Inspired by your great articles, I'm also going to upload some Ceph tutorials especially for research purpose (about how you generate a brand-new system quickly, etc.). Hope to work with you someday too!

**Comment by xuxiaopang** [comment]
Hi，there, u can contact me by QQ: 1540892727, or Email: xiaopangxu@tencent.com,
anyway, thanks for your kind reminder :smile:
